--========================================================================================================================
-- LocalizedText
--========================================================================================================================
INSERT INTO BaseGameText
		(Tag,					Text)
VALUES
--========================================================================================================================
-- Cities
--========================================================================================================================
		("LOC_CITY_NAME_SUK_GAUL_BIBRACTE",
		"비브락트"),
		("LOC_CITY_NAME_SUK_GAUL_VIENNE",
		"비엔느"),
		("LOC_CITY_NAME_SUK_GAUL_ALESIA",
		"알레시아"),
		("LOC_CITY_NAME_SUK_GAUL_GERGOVIA",
		"게르고비아"),
		("LOC_CITY_NAME_SUK_GAUL_NEMOSSOS",
		"네모소스"),
		("LOC_CITY_NAME_SUK_GAUL_LUTETIA",
		"루테티아"),
		("LOC_CITY_NAME_SUK_GAUL_CENABUM",
		"케나붐"),
		("LOC_CITY_NAME_SUK_GAUL_DUROCORTORUM",
		"두로코르토룸"),
		("LOC_CITY_NAME_SUK_GAUL_LEMONUM",
		"레모눔"),
		("LOC_CITY_NAME_SUK_GAUL_NAMNETUM",
		"남네툼"),
		("LOC_CITY_NAME_SUK_GAUL_CONDATE",
		"콘다테"),
		("LOC_CITY_NAME_SUK_GAUL_BURDIGALA",
		"부리디갈라"),
		("LOC_CITY_NAME_SUK_GAUL_VESONTIO",
		"베손티오"),
		("LOC_CITY_NAME_SUK_GAUL_ROTOMAGUS",
		"로토마구스"),
		("LOC_CITY_NAME_SUK_GAUL_SAMAROBRIVA",
		"사마로브리바"),
		("LOC_CITY_NAME_SUK_GAUL_DIVODURUM",
		"디보두룸"),
		("LOC_CITY_NAME_SUK_GAUL_SEGODUNUM",
		"세고두눔"),
		("LOC_CITY_NAME_SUK_GAUL_NEMETOCENNA",
		"네메토케나"),
		("LOC_CITY_NAME_SUK_GAUL_AUTRICUM",
		"아우트리쿰"),
		("LOC_CITY_NAME_SUK_GAUL_SUINDINUM",
		"수인디눔"),
		("LOC_CITY_NAME_SUK_GAUL_AVARICON",
		"아바리콘"),
		("LOC_CITY_NAME_SUK_GAUL_DARIORITUM",
		"다리오리툼"),
		("LOC_CITY_NAME_SUK_GAUL_AGEDINCUM",
		"아게딘쿰"),
		("LOC_CITY_NAME_SUK_GAUL_ARGENTORATE",
		"아르겐토라테"),
		("LOC_CITY_NAME_SUK_GAUL_NOVIOMAGUS",
		"노비오마구스"),
		("LOC_CITY_NAME_SUK_GAUL_BAGACUM",
		"바가쿰"),
		("LOC_CITY_NAME_SUK_GAUL_GESORIACUM",
		"게소리아쿰"),
		("LOC_CITY_NAME_SUK_GAUL_GABILLONUM",
		"가빌로눔"),
		("LOC_CITY_NAME_SUK_GAUL_TOLOSA",
		"톨로사"),
		("LOC_CITY_NAME_SUK_GAUL_LUGDUNUM",
		"루그두눔"),
		("LOC_CITY_NAME_SUK_GAUL_UXELLODUNUM",
		"욱셀로두눔"),
		("LOC_CITY_NAME_SUK_GAUL_DUROTINCON",
		"두로틴콘"),
		("LOC_CITY_NAME_SUK_GAUL_BRATUSPANTION",
		"브라투스판티온"),
		("LOC_CITY_NAME_SUK_GAUL_NOVIODUNUM",
		"노비오두눔"),
		("LOC_CITY_NAME_SUK_GAUL_DIVONA",
		"디보나"),
		("LOC_CITY_NAME_SUK_GAUL_KARNAG",
		"카르나그"),
--========================================================================================================================
-- Citizens
--========================================================================================================================
		("LOC_CITIZEN_SUK_GAUL_MALE_1",
		"세고마로스"),
		("LOC_CITIZEN_SUK_GAUL_MALE_2",
		"브렌노스"),
		("LOC_CITIZEN_SUK_GAUL_MALE_3",
		"두브노릭스"),
		("LOC_CITIZEN_SUK_GAUL_MALE_4",
		"브로기마로스"),
		("LOC_CITIZEN_SUK_GAUL_MALE_5",
		"킨투그나토스"),
		("LOC_CITIZEN_SUK_GAUL_MALE_6",
		"카투릭스"),
		("LOC_CITIZEN_SUK_GAUL_MALE_7",
		"가로마로스"),
		("LOC_CITIZEN_SUK_GAUL_MALE_8",
		"아디안투마로스"),
		("LOC_CITIZEN_SUK_GAUL_MALE_9",
		"알비오릭스"),
		("LOC_CITIZEN_SUK_GAUL_MALE_10",
		"비로갈로스"),

		("LOC_CITIZEN_SUK_GAUL_FEMALE_1",
		"데보그나타"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_2",
		"쿠노펜노스"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_3",
		"루구셀바"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_4",
		"파울라"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_5",
		"보우딜라티스"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_6",
		"루페나"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_7",
		"세베라"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_8",
		"바노나"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_9",
		"아욱티오나"),
		("LOC_CITIZEN_SUK_GAUL_FEMALE_10",
		"블라투키아"),

		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_1",
		"마르티알리스"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_2",
		"벡티토스"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_3",
		"에산데코토스"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_4",
		"안다레비세오스"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_5",
		"케레트리우스"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_6",
		"비탈스타티스틱스"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_7",
		"보두오그나투스"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_8",
		"타라니스"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_9",
		"둠노릭스"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_MALE_10",
		"카투릭스"),

		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_1",
		"안다르타"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_2",
		"에스켄가"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_3",
		"로스메르타"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_4",
		"에포나"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_5",
		"시로나"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_6",
		"아르두인나"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_7",
		"베니토우타"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_8",
		"블라투카"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_9",
		"아디에가"),
		("LOC_CITIZEN_SUK_GAUL_MODERN_FEMALE_10",
		"아베사"),
--========================================================================================================================
-- Pedia
--========================================================================================================================
-- Info
--------------------------------------------------------------------
		("LOC_CIVINFO_SUK_GAUL_LOCATION",
		"유럽"),
		("LOC_CIVINFO_SUK_GAUL_SIZE",
		"약 494,000 제곱킬로미터"),
		("LOC_CIVINFO_SUK_GAUL_POPULATION",
		"약 500만명 (로마 정복 당시)"),
		("LOC_CIVINFO_SUK_GAUL_CAPITAL",
		"없음 (갈리아의 부족들은 통일되어 있지 않았고, 각 부족은 각각의 수도를 가지고 있었다.)"),
--------------------------------------------------------------------
-- Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_1",
		"갈리아는 로마 제국의 멸망 이전까지 현재의 프랑스, 벨기에, 스위스 서부, 그리고 라인 강 서쪽의 독일을 포함하는 지방을 가리키는 말이며, 율리우스 카이사르가 본국 이탈리아에 포함시키기 전까지의 갈리아 키살피나 (알프스 이남 북부 이탈리아)도 포함되었다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_2",
		"이 지방은 기원전 58년부터 기원전 51년까지 8년간 율리우스 카이사르에 의해 평정되었으며 1세기에 이르러 갈리아 나르보넨시스, 아퀴타니아, 갈리아 루그두넨시스, 벨기카, 고지 게르마니아의 다섯 로마 속주로 나뉘었다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_3",
		"갈리아의 원 거주민은 켈트족으로, 갈리아라는 이름 자체가 '켈타이(Celtae)'를 라틴어식으로 옮긴 것이다. 갈리아의 켈트족은 수십여 개의 부족국가로 갈라져 있었는데, 이들에 대해서는 율리우스 카이사르의 '갈리아 전쟁기'에 상세히 기록되어 있다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_4",
		"갈리아인들은 260년 발레리아누스 황제가 사산 제국의 샤푸르 1세에게 사로잡힌 이후 로마 제국에서 독립해 포스투무스를 황제로 한 갈리아 제국을 건설했으나 273년 아우렐리아누스 황제 때 다시 로마 제국의 일부가 되었다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_5",
		"로마인들은 갈리아를 두 개의 지역으로 구분하였는데, 알프스 산맥 이 쪽 지역의 갈리아 즉 포강 유역을 갈리아 키살피나라고 부르고, 알프스 산맥 너머의 갈리아 즉 유럽의 먼 나머지 지역을 갈리아 트란살피나라고 불렀다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_GAUL_CHAPTER_HISTORY_PARA_6",
		"갈리아 지방은 포도주가 크게 발달하였으므로 로마산 포도주가 갈리아산 포도주에 밀릴 것을 우려한 로마 황제가 한때 포도 생산을 금지시키기도 하였다.");
--========================================================================================================================
--========================================================================================================================