--========================================================================================================================
-- LocalizedText
--========================================================================================================================
INSERT OR REPLACE INTO BaseGameText
		(Tag,					Text)
VALUES
--========================================================================================================================
-- SIAM
--========================================================================================================================
		("LOC_CIVILIZATION_SUK_SIAM_NAME",  
		"시암"	),
		("LOC_CIVILIZATION_SUK_SIAM_DESCRIPTION",  
		"시암 제국"	),
		("LOC_CIVILIZATION_SUK_SIAM_ADJECTIVE",  
		"시암의"	),	
    --------------------------------------------------------------------
    -- UA
    --------------------------------------------------------------------
		("LOC_TRAIT_CIVILIZATION_SUK_SRI_AYUTTHAYA_NAME",  
		"스리 아유타야"	),
		("LOC_TRAIT_CIVILIZATION_SUK_SRI_AYUTTHAYA_DESCRIPTION",  
		"강 옆에 지어진 도시는 [ICON_Housing] 주거 공간 +2와 [ICON_Amenities] 쾌적도 +1을 얻습니다. 강에 인접한 특수지구는 [ICON_Food] 식량 +1을 제공합니다. [ICON_Envoy] 사절을 제공하는 사회 제도로부터 [ICON_Envoy] 사절 1명을 추가로 얻습니다."), 
    --------------------------------------------------------------------
    -- Cities
    --------------------------------------------------------------------
		("LOC_CITY_NAME_SIAM_KRUNG_THEP",
		"크룽 텝"),
		("LOC_CITY_NAME_SIAM_AYUTTHAYA",
		"아유타야"),
		("LOC_CITY_NAME_SIAM_SUKHOTHAI",
		"수코타이"),
		("LOC_CITY_NAME_SIAM_PHITSANULOK",
		"핏사눌록"),
		("LOC_CITY_NAME_SIAM_CHIANG_MAI",
		"치앙 마이"),
		("LOC_CITY_NAME_SIAM_NAKHON_SI_THAMMARAT",
		"나콘 시 탐마랏"),
		("LOC_CITY_NAME_SIAM_LAMPANG",
		"람팡"),
		("LOC_CITY_NAME_SIAM_KAMPHAENG_PHET",
		"깜팽펫"),
		("LOC_CITY_NAME_SIAM_RATCHABURI",
		"랏차부리"),
		("LOC_CITY_NAME_SIAM_LOPBURI",
		"롭부리"),
		("LOC_CITY_NAME_SIAM_CHIANG_RAI",
		"치앙 라이"),
		("LOC_CITY_NAME_SIAM_NAKHON_RATCHASIMA",
		"나콘 랏차시마"),
		("LOC_CITY_NAME_SIAM_NAKHON_SAWAN",
		"나콘 사완"),
		("LOC_CITY_NAME_SIAM_NONTHABURI",
		"논타부리"),
		("LOC_CITY_NAME_SIAM_UBON_RATCHATHANI",
		"우본 랏차타니"),
		("LOC_CITY_NAME_SIAM_UDON_THANI",
		"우돈 타니"),
		("LOC_CITY_NAME_SIAM_NAKHON_PATHOM",
		"나콘 빠톰"),
		("LOC_CITY_NAME_SIAM_KANCHANABURI",
		"깐짜나부리"),
		("LOC_CITY_NAME_SIAM_KHON_KAEN",
		"콘깬"),
		("LOC_CITY_NAME_SIAM_SURIN",
		"수린"),
		("LOC_CITY_NAME_SIAM_PHIMAI",
		"피마이"),
		("LOC_CITY_NAME_SIAM_PHETCHABURI",
		"펫차부리"),
		("LOC_CITY_NAME_SIAM_SI_SATCHANALAI",
		"시 사차날라이"),
		("LOC_CITY_NAME_SIAM_NAN",
		"난"),
		("LOC_CITY_NAME_SIAM_BURIRAM",
		"부리람"),
		("LOC_CITY_NAME_SIAM_NONG_BUA_LAMPHU",
		"농 부아 람푸"),
		("LOC_CITY_NAME_SIAM_CHAIYAPHUM",
		"차이야품"),
		("LOC_CITY_NAME_SIAM_HAT_YAI",
		"핫야이"),
		("LOC_CITY_NAME_SIAM_PAK_KRET",
		"빡 끄렛"),
		("LOC_CITY_NAME_SIAM_PATTAYA",
		"파타야"),
		("LOC_CITY_NAME_SIAM_SONGKHLA",
		"송클라"),
		("LOC_CITY_NAME_SIAM_SURAT_THANI",
		"수랏 타니"),
		("LOC_CITY_NAME_SIAM_YALA",
		"얄라"),
		("LOC_CITY_NAME_SIAM_PHUKET",
		"뿌껫"),
		("LOC_CITY_NAME_SIAM_SAMUT_PRAKAN",
		"사뭇 쁘라칸"),
		("LOC_CITY_NAME_SIAM_TRANG",
		"뜨랑"),
		("LOC_CITY_NAME_SIAM_SAMUI",
		"사무이"),
		("LOC_CITY_NAME_SIAM_SAMUT_SAKHON",
		"사뭇 사콘"),
		("LOC_CITY_NAME_SIAM_RAYONG",
		"라용"),
		("LOC_CITY_NAME_SIAM_MAE_SOT",
		"매 솟"),
		("LOC_CITY_NAME_SIAM_OM_NOI",
		"옴 노이"),
		("LOC_CITY_NAME_SIAM_SAKON_NAKHON",
		"사꼰 나콘"),
    --------------------------------------------------------------------
    -- Citizens
    --------------------------------------------------------------------
		("LOC_CITIZEN_SUK_SIAM_MALE_1",
		"윳"),
		("LOC_CITIZEN_SUK_SIAM_MALE_2",
		"댕"),
		("LOC_CITIZEN_SUK_SIAM_MALE_3",
		"싱"),
		("LOC_CITIZEN_SUK_SIAM_MALE_4",
		"시리"),
		("LOC_CITIZEN_SUK_SIAM_MALE_5",
		"솜분"),
		("LOC_CITIZEN_SUK_SIAM_MALE_6",
		"람"),
		("LOC_CITIZEN_SUK_SIAM_MALE_7",
		"뜨리"),
		("LOC_CITIZEN_SUK_SIAM_MALE_8",
		"통"),
		("LOC_CITIZEN_SUK_SIAM_MALE_9",
		"품"),
		("LOC_CITIZEN_SUK_SIAM_MALE_10",
		"나렛"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_1",
		"수다"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_2",
		"부아"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_3",
		"나리"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_4",
		"마니"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_5",
		"말리"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_6",
		"룽"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_7",
		"와니"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_8",
		"핌"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_9",
		"솜짓"),
		("LOC_CITIZEN_SUK_SIAM_FEMALE_10",
		"루디"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_1",
		"아피싯"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_2",
		"수끄릿"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_3",
		"카시디스"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_4",
		"타나콘"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_5",
		"차나품"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_6",
		"탐마탓"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_7",
		"위사루테"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_8",
		"끄리앙삭"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_9",
		"나롱차이"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_MALE_10",
		"타나삭"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_1",
		"앙칼리포른"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_2",
		"파라디"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_3",
		"판팁"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_4",
		"차냐"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_5",
		"수파마르트"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_6",
		"아리사"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_7",
		"짓수파"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_8",
		"나띠라"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_9",
		"찻나파"),
		("LOC_CITIZEN_SUK_SIAM_MODERN_FEMALE_10",
		"아티타야"),
    --------------------------------------------------------------------
    -- Named Places
    --------------------------------------------------------------------
		("LOC_NAMED_RIVER_CHAO_PHRAYA_NAME",				"짜오프라야강"),
		("LOC_NAMED_RIVER_PING_NAME",						"핑강"),
		("LOC_NAMED_RIVER_NAN_NAME",						"난강"),
		("LOC_NAMED_RIVER_WANG_NAME",						"왕강"),
		("LOC_NAMED_RIVER_YOM_NAME",						"욤강"),
		("LOC_NAMED_RIVER_PA_SAK_NAME",						"빠삭강"),
		("LOC_NAMED_RIVER_MUN_NAME",						"문강"),
		("LOC_NAMED_MOUNTAIN_DAEN_LAO_NAME",				"댄 라오 산맥"),
		("LOC_NAMED_MOUNTAIN_LUANG_PRABANG_NAME",			"루앙 프라방 산맥"),
		("LOC_NAMED_MOUNTAIN_THANON_THONG_CHAI_NAME",		"타농 통 차이 산맥"),
		("LOC_NAMED_MOUNTAIN_PHI_PAN_NAM_NAME",				"피 남 반 산맥"),
		("LOC_NAMED_MOUNTAIN_PETCHABUN_NAME",				"펫차분 산맥"),
		("LOC_NAMED_MOUNTAIN_SANKHAMPHAENG_NAME",			"싼깜팽 산맥"),
		("LOC_NAMED_MOUNTAIN_BANTHAT_NAME",					"반탓 산맥"),
		("LOC_NAMED_MOUNTAIN_SANKALAKHIRI_NAME",			"싼깔라키리 산맥"),
		("LOC_NAMED_MOUNTAIN_TENASSERIM_NAME",				"테나세림 산맥"),
		("LOC_NAMED_VOLCANO_DOI_PHA_KHOK_HIN_FUU_NAME",		"도이 파콕힌 화산"),

		("LOC_NAMED_LAKE_BUENG_BORAPHET_NAME",		"붕 보라펫"),
		("LOC_NAMED_LAKE_SONGKHLA_NAME",			"송클라 호"),
		("LOC_NAMED_LAKE_PHAYAO_NAME",				"파야오 호"),
		("LOC_NAMED_LAKE_NONG_HAN_NAME",			"농 한"),
		("LOC_NAMED_SEA_KRUNG_THEP_BAY_NAME",		"크룽 텝 만"),
		("LOC_NAMED_SEA_PHANG_NGA_BAY_NAME",		"팡 응아 만"),
		("LOC_NAMED_SEA_PRACHUAP_BAY_NAME",			"쁘라쭈압 만"),
		("LOC_NAMED_SEA_SATTAHIP_BAY_NAME",			"사따힙 만"),
		("LOC_NAMED_SEA_BANDON_BAY_NAME",			"반돈 만"),
		("LOC_NAMED_SEA_MANAO_BAY_NAME",			"마나오 만"),
    --------------------------------------------------------------------
    -- Info
    --------------------------------------------------------------------
		("LOC_CIVINFO_SUK_SIAM_LOCATION",
		"아시아"),
		("LOC_CIVINFO_SUK_SIAM_SIZE",
		"약 513,100 제콥킬로미터"),
		("LOC_CIVINFO_SUK_SIAM_POPULATION",
		"2015년 약 6790만 명"),
		("LOC_CIVINFO_SUK_SIAM_CAPITAL",
		"다양(수코타이, 핏사눌록, 아유타야, 롭부리, 톤부리, 현재는 크룽 템/방콕)"),
	--------------------------------------------------------------------
	-- Pedia
	--------------------------------------------------------------------
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_1",
		"동남아시아의 버마(미얀마), 라오스, 캄보디아, 말레이시아 사이에 있는 시암(오늘날의 태국)은 길고 유명한 역사를 갖고 있다. 아름답고 신비로운 울창한 삼림과 태곳적 산맥을 가진 시암은 점령과 혁명, 홍수와 기근, 제국의 흥망성쇠를 지켜보았다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_2",
		"시암의 가장 오래된 정착민은 몬크메르어를 사용했다. 동남아시아 반도에는 몇 가지 다른 부족이 있다. 하나는 몬 족으로, 서기 6세기에 불교를 수용한 것으로 알려졌다. 다른 부족은 크메르로 주로 캄보디아에 있었고 수도는 앙코르였다. 앙코르와트가 있는 곳이다. 12세기에 크메르는 현대 태국의 절반을 아우르는 제국을 소유했다. 그들은 불교보다는 힌두교를 더 따랐다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_3",
		"서기 1000년경에 이 지역에는 타이어를 쓰는 '타이' 민족이 유입되었다. 오늘날의 역사가들은 대부분 타이족이 북부 베트남에서 이주해왔다고 생각한다. 몇 세기도 안 되어 타이족은 동남아시아 전역에 퍼져서 서쪽으로는 인도 북동부까지, 남쪽으로는 말레이 반도까지 진출했다. 13세기경에는 시암에서 몬 족과 크메르 족의 버금가는 세력을 이룰 만큼 수가 많아졌다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_4",
		"13세기 중반 타이족의 지배자는 크메르 제국에 반기를 들고 수코타이 왕국을 창건했다. 수코타이 왕국은 1279년에 세 번째 지도자 람캄행이 즉위할 때까지 작고 별 볼 일 없는 소국이었다. 20년이라는 짧은 기간 안에 이 뛰어난 지도자는 작은 수코타이 소국을 거대한 동남아시아 지역의 강자로 탈바꿈시켰다.[NEWLINE][NEWLINE]통치 동안 람캄행은 왕국 영토를 서쪽으로는 버마, 동쪽으로는 라오스, 남쪽으로는 말레이 반도까지 확장시켰다. 왕은 전쟁 군주로서의 능력만큼이나 기민한 외교관이었다. 많은 영토가 자발적으로 람캄행의 연합에 들어왔다. 통치 말기에 람캄행은 자신의 승리를 기록한 기념비를 세웠다. 기념비에는 경애 받는 자애로운 왕이 통치하는 부유하고 행복한 왕국이 그려져 있다. 람캄행은 1298년에 사망했다. 수코타이는 위대한 지도자의 죽음 이후로 한 세기 동안 더 지속하였으며, 남쪽에서 일어난 새로운 타이 세력인 아유타야 왕조에 먹혔다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_5",
		"아유타야 왕국은 1351년에 라마티보디 1세가 짜오프라야 강 유역에 건국했다. 짜오프라야 강 유역은 현재 방콕 북부에 있는 비옥한 평야 지대이다. 왕국은 이전 왕조 라보의 잔해 위에 세워졌다. 1352년 라마티보디 왕은 크메르를 공격하여 시암 동쪽 밖으로 몰아냈다. 1387년 야유타야 왕조는 북부를 지배하고 있는 수코타이를 공격할 만큼 강해졌다. 그리고 1431년, 왕국은 다시 한 번 크메르를 공격하였으며, 이번에는 7달에 걸친 공성 끝에 수도인 앙코르를 점령하여 약탈했다. 아유타야의 도시는 아름답고 부유했다고 한다. 북쪽과 남쪽으로 뻗은 수로가 도시를 가로지르며 모든 지역에 물을 공급했다. 장대한 궁전과 사원 등의 유적을 오늘날에도 볼 수 있다. 아유타야 왕조 타이는 '시암'이라 불린 첫 번째 사람이며, 이게 바로 나라의 이름이 되었다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_6",
		"아유타야 왕조는 크메르로부터 왕의 신성성에 대한 믿음을 수용했다. 왕은 만인의 위에 있었다. 누구도 왕의 얼굴을 바라볼 수 없었으며, 왕실의 일원만이 예외였다. 게다가 왕의 종교적이고 의식적인 권한이 증가하면서 트라일록 왕(1448-1488)은 왕의 손안에 정치적 권력을 집중시키도록 지역을 재조직했다. 사회적으로 아유타야인들은 각 계급에 따라 수로 나타낸 가치를 부여한 엄격한 신분 제도 안에 살았다. 노예는 '사크디나'라고 부르는 단위 다섯 개의 가치가 있었고, 자유민은 25개 이상, 왕위후계자는 대략 100,000개쯤 되었다. 왕 본인은 아마 수억 수천만, 혹은 그 이상의 가치가 있었을 것이라고 역사학자들은 추측한다. 종교는 불교와 힌두교 모두 다 믿을 수 있었다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_7",
		"북쪽에서 수코타이를, 동남쪽에서 크메르를 상대해야 했지만 아유타야 왕조의 가장 큰 위협은 서쪽의 버마에 있었다. 1569년 아유타야 왕조는 버마에 정복당했다가 16세기 말에 독립을 얻었다. 버마 군은 1767년에 다시 한 번 도시를 약탈했다. 이번에는 왕가를 강제 추방하고 도시를 잿더미로 만든 뒤 아유타야의 모든 예술품과 역사 기록을 파괴했다. 아유타야 왕국은 이 피해에서 두 번 다시 회복하지 못했다. 그러나 새로운 시암 왕조가 아유타야의 잿더미 속에서 빠르게 세력을 일으켰다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_8",
		"1767년, 아유타야 최후의 파괴가 일어났던 그 해에, 탁신이라는 이름의 타이 지도자가 현재의 방콕에 있던 아유타야에서 약 64킬로미터쯤 내려간 톤부리에 새로운 수도를 창건했다. 짜오프라야 강 동쪽에 세운 도시는 버마군을 방어하기 쉽고 외해가 가까워서 국제 교류에 알맞았다. 탁신은 톤부리에서 교역하도록 중국 상인들을 장려했으며 이 교역에서 얻은 세금 수입은 최근의 버마 공격으로 황폐해진 시암 경제를 재건하는 데 쓰였다. 탁신은 국가의 부를 이용하여 강력한 군대를 건설하고 영토를 넓히기 시작했다. 수코타이와 아유타야가 보유했던 영토를 되찾고 난 뒤에 탁신의 군대는 라오스의 영토를 추가 정복했고, 버마군은 이전 타이 영토 밖 북쪽으로 몰아냈다. 1782년 탁신은 심각한 정신병의 징후를 보이기 시작했으며 전복당해 살해되었다. 짜오프라야 차크리라는 장군이 뒤를 이었으며, 그는 후에 이름을 라마 1세로 바꾼다. 차크리 왕조는 현대까지 태국 왕실로 남아 있다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_9",
		"옥좌를 이어받은 새 왕은 수도를 짜오프라야 강 건너 작은 마을인 방콕으로 옮겼다. 방콕은 금세 북적거리는 교역 도시로 성장하였는데, 대도시로 이주해온 중국인(화교)들 덕이 컸다. 라마 1세와 그 후계자들은 라오스와 남쪽 말레이 반도로 시암의 세력을 계속 확장했다. 또한, 오래된 위협으로 남아 있는 버마와도 계속 충돌했다. 버마는 인도에서부터 접근해온 영국에 위협받았다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_10",
		"라마 1세는 시암 문화, 종교, 법률의 위대한 후원자이기도 했는데 그는 시암 사원과 왕성을 재건하고, 시암의 법 제도를 크게 갱신했다. 후계자로서 1809년부터 1824년까지 통치한 라마 3세는 예술의 후원자로 그 자신도 대단한 시인이었다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_11",
		"시암의 외교가 거둔 가장 위대한 승리는 아마도 다른 동남아시아국과 다르게 서양 강국들의 점령을 피한 일일 것이다. 1826년 시암은 영국과 조약을 맺었으며, 1855년에 이 조약은 시암 항구에서 영국의 제한 없는 면세 무역을 허용하는 것으로 확장되었다. 영국은 또한 영국민이 관련된 사건을 심판하는 법정을 따로 세울 권리를 얻었다. 이는 시암의 권위와 수익에 치욕적인 손실이었지만 영국이 침략하여 나라를 점령하는 사태를 막았다. 그리고 시암은 곧 다른 유럽 강국 및 미국과 유사한 조약을 맺었다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_12",
		"1851년부터 1868년까지 통치한 라마 4세는 서양 문화를 열정적으로 배우는 학생이었다. 그는 궁정에 여러 서양인 고문을 임명했다. 그는 또한 영국 여인 안나 헤리트 로웬스를 고용하여 아이들을 가르치게 했다. 로웬스 부인은 나중에 자신의 모험에 대한 책을 썼으며, 그 책이 뮤지컬 '왕과 나'의 토대가 되었다. 책과 뮤지컬 둘 다 매우 오락적이며 매우 부정확하다는 것이 역사학자들의 의견이다. 시대와 지역을 생각했을 때 여러 측면에서 라마 4세는 상당히 깨어 있었다. 왕좌를 이어받기 전에 수도승이었던 그는 불교가 부패하고 미신으로 차있다고 생각하고 나라의 불교를 개편하려고 했다. 또한, 시암 왕조를 다시 만들기 시작하면서 왕조로부터 부담스러운 신성의 덫을 제거했다. 비록 그 자신은 절대적인 지배자로 남아 있었지만, 최소한 백성은 왕을 똑바로 바라볼 수 있었다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_13",
		"라마 4세의 아들, 라마 5세는 1868년부터 1910년까지 통치했다. 5세는 서양에게 양보하여 나라의 독립을 유지하는 아버지의 정책을 지속했으며, 프랑스에 라오스와 캄보디아 땅덩어리를, 영국에 말레이시아 여러 지역을 잃었다. 그는 왕조와 정부를 더 개편하여, 노예제를 폐지하고 현대적인 교육 제도를 도입했으며, 철도와 전신을 건설하고 새로운 법정과 사법부를 세웠다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_14",
		"라마 5세의 두 후계자인 라마 6세(1910-1925 통치)와 라마 7세(1925-1935 통치)는 시암의 현대화를 이어나갔다. 1917년 라마 6세는 태국에 최초의 대학을 열었다. 그 해 연합국 편에서 제1차 세계대전에 참가했는데, 전쟁 이후에 승전국들을 설득해서 그들이 시암 왕국에 가진 특별 혜택을 포기하도록 했고, 75년 만에 처음으로 태국의 완전한 독립을 얻어냈다. 그러나 라마 6세의 개편과 전쟁에 큰 비용이 들었고, 정부 지출을 삭감할 수밖에 없게 되었으며, 국민의 큰 분노를 일으켰다. 이 불만은 그 후계자의 통치 기간에도 이어졌고 대공황으로 말미암아 더욱 악화되었다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_15",
		"1932년 프리디 파놈용이라는 변호사가 이끄는 일단의 학생들이 시암 군부의 지지를 받아 무혈 쿠데타를 일으키고 왕에게 헌법 아래에서 통치하며 국민 의회 설립을 수용할 것을 강요했다. 1933년 왕실 일원들이 반 쿠데타를 시도했으나 실패하고, 라마 7세는 나라를 떠나 1935년에 퇴위해야 했다. 너무 어린 아난다 마히돌 왕자가 나이가 찰 때까지 섭정 의회가 임명되었다. 그러나 사실상 군부가 나라를 운영하고 있었다. 1938년 한 육군 원수와 라마 7세를 쫓아냈던 32년 쿠데타의 공포자 중 하나가 군사 독재자가 되었다. 독재자 피분 송크람은 나라 이름을 태국으로 바꾸고, 태국 민족주의는 물론 반중친일 감정을 조장했다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_16",
		"1940년, 독일이 프랑스를 점령한 후에 프랑스 영토인 라오스와 캄보디아를 침략하여 점령했다. 1941년 말, 진주만 공격 이후에 일본군은 태국으로 진격하여 영국이 점령하고 있던 싱가포르를 공격하기 위해 나라를 가로지르는 길을 터 달라고 요구했다. 타이군은 최소한의 형식적인 저항을 한 뒤에 무기를 내려놓았다. 1942년 태국은 일본과 동맹을 맺고 영국과 미국에 전쟁을 선포했다. 국내와 국외에 형성된 저항 집단은 일본인과 협력하는 태국 정부를 공격했다. 1944년 7월 피분은 사임하였고, 독재 정권은 1945년 일본의 항복 이후에 무너졌다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_17",
		"태국은 제2차 세계대전 후에 상대적으로 가볍게 출발했다. 프랑스에서 빼앗아 날름 삼킨 영토를 돌려줘야 하긴 했지만 대체로 다른 불이익은 없었다. 그러나 태국은 엄청난 내부 분쟁에 시달렸다. 1946년 왕이 총상을 입고 죽은 채로 발견되었다. 당시 정부 지도자는 왕의 죽음에 대한 책임을 비난받고 추방당했으며, 원형 파시스트 독재자인 피분 송크람이 권좌로 돌아왔다. 냉전시대에 미국은 태국에 막대한 돈을 쏟아부었는데, 대부분 군부와 독재자가 가져갔다. 국가 산업의 대부분은 독재자와 그 일당이 소유하고 있었으며, 1957년 군부가 또 쿠데타를 일으켜서 새로운 육군 원수 사릿 타나랏을 자리에 앉혔다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_18",
		"타나랏은 5년 동안 집권했다. 그는 정부와 군부에 대한 완전한 권력을 유지하는 동시에 성장하는 태국 중산층에 부를 분배하는 경제 개혁을 시행하여 상당한 민중의 지지를 얻었다. 미국은 그에게 더 많은 돈을 주었고, 그 돈을 군부를 지원하는데에도 썼지만, 태국의 기반 시설을 향상하기도 했다. 나타랏은 또한, 당시에 아무런 정치력이 없었던 왕실도 지원하였고, 왕가가 다시 한 번 태국 민족주의의 강력한 상징이 되었다. 생전에 인기 있는 지도자였던 그는 사후에 집권하는 동안 얼마나 많은 태국의 돈을 훔치고 빼돌렸는지 알려지면서 인기가 시들해졌다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_19",
		"타나랏의 후계자는 계속 엄청난 미국의 지원금을 받으면서 그 대가로 베트남의 미국 원정을 지원했다. 1960년대 말쯤에는 1만 명이 넘는 태국 군대가 베트남에 참전하고 있었으며, 수천 명의 미국군이 미국 공군에게 중요한 기치를 제공해준 태국에 주둔했다. 전쟁과 정부에 대한 대중의 불만이 커지면서 1973년 학생이 주도한 반란으로 당시 지도자를 추방했다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_20",
		"태국은 짧은 시간이나마 의회 민주주의를 누렸다. 1976년 군부가 또 쿠데타를 일으켰고 이번에는 왕실의 지원을 받고 있었다. 결국, 이 쿠데타로 불만을 품은 많은 태국인이 정글로 들어가 태국의 반란 공산당이 커지게 되었다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_21",
		"1980년 군부는 막 설치한 우익 정부를 몰아내고 더 민주주의적 성향을 띤 독재자로 바꾸었다. 이후 8년 동안 군부는 의회와 권력을 양분하면서 왕의 중재를 받았다. 1988년 투표로 선출된 수상이 권좌에 3년 동안 앉았다가 군부에 실각되었다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_22",
		"1992년에 군사정부가 선거를 열었으며, 군부의 인물이 당선되었고 이에 대해 아무도 놀라지 않았다. 대중은 이 결과에 불만을 품고 대규모 시위를 벌였으며, 무력으로 진압되었다. 마침내 왕이 개입하여 독재자가 사임하고 더 민주주의적인 정부가 들어섰다. 이 정부는 영광스럽게 8년 동안 지속되었는데 2006년 민중의 불만 증가와 정부의 전횡으로 또 군부 쿠데타가 일어났다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_23",
		"나이든 왕이 물러나면서 다른 정부가 은퇴한 장성을 지도자로 해서 만들어졌다. 또다시 새로운 헌법이 제정되고 2007년 8월에 국민투표로 비준되었다. 2008년 9월에 솜차이 웡사왓 총리가 이익충돌 죄로 헌법재판소에서 유죄 판결을 받았다. 10월에 수상의 후임은 시위자들이 사무실을 점거하는 바람에 들어갈 수가 없었다. 그래서 그는 공직에서 쫓겨났다."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_SIAM_CHAPTER_HISTORY_PARA_24",
		"태국은 입헌군주정이며, 기본적으로 의회민주주의를 채택하고 있다. 허나 역사적으로 태국은 수많은 쿠데타와 군사 독재를 거치며 현재까지도 제대로 된 민주주의를 실현하고 있지 못하다는 평가를 받고 있다. 2000년대에는 탁신 친나왓 총리의 지지자들과 반대자들의 갈등으로 얼룩졌으며, 가장 최근에는 2014년의 쿠데타로 인해 현행 20차 헌법이 통용되고 있다.");
--========================================================================================================================
--========================================================================================================================