-- Honey_Maize_ForNonNFP_Text
-- Author: Amatheria
-- DateCreated: 1/26/2021 2:35:38 AM
--------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------
-- BaseGameText
----------------------------------------------------------------------------------------------------------------------------
INSERT OR IGNORE INTO BaseGameText
		(Tag,										Text,																		Gender) 
VALUES	('LOC_RESOURCE_HONEY2_NAME',				'벌꿀',																	'Masculine:no_article'),
		('LOC_PEDIA_RESOURCES_PAGE_RESOURCE_HONEY2_CHAPTER_HISTORY_PARA_1',		'맛있는 음식.',				NULL),
		('LOC_RESOURCE_MAIZE2_NAME',				'옥수수',																'Masculine:no_article'),
		('LOC_PEDIA_RESOURCES_PAGE_RESOURCE_MAIZE2_CHAPTER_HISTORY_PARA_1',		'곡식.',				NULL);
		
----------------------------------------------------------------------------------------------------------------------------
-- LocalizedText
----------------------------------------------------------------------------------------------------------------------------
INSERT OR IGNORE INTO LocalizedText
		(Tag,										Language,		Text,																		Gender) 
VALUES	('LOC_RESOURCE_HONEY2_NAME',				'de_DE',		'Honig',																	'Masculine:no_article'),
		('LOC_PEDIA_RESOURCES_PAGE_RESOURCE_HONEY2_CHAPTER_HISTORY_PARA_1',		'de_DE',		'Honig (lateinisch und apothekersprachlich Mel) ist ein von Honigbienen zur eigenen Nahrungsvorsorge erzeugtes und vom Menschen genutztes Lebensmittel aus dem Nektar von Blüten oder den zuckerhaltigen Ausscheidungsprodukten verschiedener Insekten, dem sogenannten Honigtau. [NEWLINE][NEWLINE]Schon in der Steinzeit nutzte der Mensch Honig als Nahrungsmittel, wie es 9000 Jahre alte steinzeitliche Höhlenmalereien mit „Honigjägern“ zeigen. Er war zunächst das einzige Süßungsmittel. Der wild lebenden Bienenvölkern abgenommene Honig wurde auch als Köder bei der Bärenjagd eingesetzt. Australische Petroglyphen zeigen, dass die Aborigines bereits in vorgeschichtlicher Zeit Buschhonig von stachellosen Bienen sammelten. Der Ursprung der Hausbienenhaltung mit geplanter Honiggewinnung wird im 7. Jahrtausend v. Chr. in Anatolien vermutet.[3] Bei Ausgrabungen von Pharaonengräbern in Ägypten wurde Honig als Grabbeigabe gefunden. Um 3000 v. Chr. galt im Alten Ägypten Honig als „Speise der Götter“ und als Quelle der Unsterblichkeit: Ein Topf Honig hatte einen Wert vergleichbar dem eines Esels. Um 400 v. Chr. lehrte Hippokrates, dass Honigsalben Fieber senken und dass Honigwasser die Leistung der Athleten bei den antiken Olympischen Spielen verbesserte. Nach Augustinus ist der Honig ein Bild für die Zärtlichkeit Gottes und seine Güte. Im Koran wird die Heilwirkung des Honigs beschrieben. In der 16. Sure (an-Nahl, auf Deutsch: Die Biene), Vers 68–69, wird berichtet, dass „die Biene durch Eingebung den Befehl bekommen hat, von allen Früchten zu essen und dadurch Honig herzustellen und dass der Honig für den Menschen eine Heilwirkung besitzt“.[4] In einem Kochbuch von 1547 spricht der Autor auch von den damals angenommenen Wirkungen: „Rosenhonig sterket und reinigt den magen/von böser feuchtigkeit/reiniget und heilet gschwer/Feul und Schaden des Munds/Zahnfleisch/Hals und Gurgeln“. Bevor Zucker industriell aus Zuckerrüben gewonnen wurde, war Honig ein wichtiger, oft auch der einzige Süßstoff. Infolge der Entwicklung von Verfahren zur Herstellung von Haushaltszucker (reine Saccharose) aus Zuckerrüben und Zuckerrohr ist Honig in dieser Hinsicht weitgehend verdrängt worden. In der modernen, weiterverarbeitenden Lebensmittelindustrie spielt er fast keine Rolle mehr. Trotzdem wird Honig als Nahrungsmittel weiterhin geschätzt, zum Beispiel als süßer Brotaufstrich oder als Alternative zum industriell hergestellten Haushaltszucker.',				NULL),
		('LOC_RESOURCE_MAIZE2_NAME',				'de_DE',		'Mais',																'Masculine:no_article'),
		('LOC_PEDIA_RESOURCES_PAGE_RESOURCE_MAIZE2_CHAPTER_HISTORY_PARA_1',		'de_DE',		'Mais (Zea mays), in Teilen Österreichs und Altbayerns auch Kukuruz (aus dem Slawischen) genannt, ist eine Pflanzenart innerhalb der Familie der Süßgräser (Poaceae). Das Getreide stammt ursprünglich aus Mexiko und ist eine einhäusig getrenntgeschlechtige C4-Pflanze. [NEWLINE][NEWLINE]Der Körnermais ist eines der Grundnahrungsmittel der Bevölkerung Afrikas und Lateinamerikas. Das glutenfreie Getreide ist zudem auch für Personen mit Überempfindlichkeit gegen Klebereiweiß (Zöliakie) tauglich. Neben der Verarbeitung in der Lebensmittelindustrie wird die aus Mais gewonnene Stärke als nachwachsender Rohstoff für die Herstellung von bio-basierten Kunststoffen eingesetzt.',				NULL),
		('LOC_RESOURCE_HONEY2_NAME',				'es_ES',		'Miel',																	'Masculine:no_article'),
		('LOC_PEDIA_RESOURCES_PAGE_RESOURCE_HONEY2_CHAPTER_HISTORY_PARA_1',		'es_ES',		'Ojito con este bicho.',				NULL),
		('LOC_RESOURCE_MAIZE2_NAME',				'es_ES',		'Maíz',																'Masculine:no_article'),
		('LOC_PEDIA_RESOURCES_PAGE_RESOURCE_MAIZE2_CHAPTER_HISTORY_PARA_1',		'es_ES',		'Cereal.',				NULL),
		('LOC_RESOURCE_HONEY2_NAME',				'ru_RU',		'Мёд',																	'Masculine:no_article'),
		('LOC_PEDIA_RESOURCES_PAGE_RESOURCE_HONEY2_CHAPTER_HISTORY_PARA_1',		'ru_RU',		'Мёд (Mel на латыни и языке фармацевтов) - это пища, производимая медоносными пчелами для собственного питания и используемая людьми из нектара цветов или сахаристых выделений различных насекомых, так называемой медвяной росы.[NEWLINE][NEWLINE]Уже в каменном веке люди использовали мёд в пищу, как показано на наскальных рисунках 9000-летней давности с изображением «Охотников за медом». Сначала это был единственный подсластитель. Мед, взятый из семей диких пчел, также использовался в качестве приманки для охоты на медведя. Австралийские петроглифы показывают, что аборигены собирали кустовой мед у безжалостных пчел еще в доисторические времена. Зарождение домашнего пчеловодства с плановым производством меда относится к 7 тысячелетию до нашей эры. В Анатолии.[3]При раскопках гробниц фараонов в Египте мед был найден как объект захоронения. Около 3000 г. до н.э. В Древнем Египте мед считался «пищей богов» и источником бессмертия: горшок с медом имел ценность, сопоставимую с ценой осла. Около 400 г. до н.э. В Британской Колумбии Гиппократ учил, что медовые мази уменьшают лихорадку, а вода с медом улучшает результаты спортсменов на древних Олимпийских играх. По словам Августина, мед - это образ Божьей нежности и доброты. Лечебные свойства меда описаны в Коране. В 16-й суре (ан-Нахль, на немецком языке: Die Biene), стихи 68-69, сообщается, что «пчела была повелена вдохновением съесть все плоды и таким образом произвести мед, и что мед оказывает лечебный эффект. на людей ».[4]В кулинарной книге 1547 года автор также говорит об эффектах, предполагаемых в то время: «Розовый мед укрепляет и очищает желудок/от плохой влаги/очищает и лечит тяжелые/болезненные ощущения и повреждения рта/десен/горла и полоскания горла». До того, как сахар из сахарной свеклы начали промышленно производить, мед был важным и часто единственным подсластителем. В результате разработки процессов производства домашнего сахара (чистой сахарозы) из сахарной свеклы и сахарного тростника мёд в этом отношении в значительной степени вытеснился. В современной перерабатывающей пищевой промышленности это уже не играет роли. Тем не менее, мед по-прежнему ценится как продукт питания, например, как сладкое намазывание, или как альтернатива промышленно производимому домашнему сахару.',				NULL),
		('LOC_RESOURCE_MAIZE2_NAME',				'ru_RU',		'Кукуруза',																'Masculine:no_article'),
		('LOC_PEDIA_RESOURCES_PAGE_RESOURCE_MAIZE2_CHAPTER_HISTORY_PARA_1',		'ru_RU',		'Кукуруза (Zea mays), также называемая Кукуруз (от славянского) в некоторых частях Австрии и Старой Баварии, относится к семейству сладких трав (Poaceae). Зерно родом из Мексики и является однополым однополым растением C4. [NEWLINE] [NEWLINE] Зерновая кукуруза - один из основных продуктов питания жителей Африки и Латинской Америки. Каша без глютена также подходит для людей с повышенной чувствительностью к глютену (целиакия). Помимо обработки в пищевой промышленности, крахмал, полученный из кукурузы, используется в качестве возобновляемого сырья для производства пластмасс на биологической основе.',				NULL);