--========================================================================================================================
-- LocalizedText
--========================================================================================================================
INSERT OR REPLACE INTO BaseGameText
		(Tag,					Text)
VALUES
--========================================================================================================================
-- Burma
--========================================================================================================================
		("LOC_CIVILIZATION_SUK_BURMA_NAME",  
		"버마"	),
		("LOC_CIVILIZATION_SUK_BURMA_DESCRIPTION",  
		"버마 제국"	),
		("LOC_CIVILIZATION_SUK_BURMA_ADJECTIVE",  
		"버마의"	),
		-- RWF
		("LOC_CIVILIZATION_SUK_BURMA_DESCRIPTION_JFD_CIVILIZATION",
		"버마 문명"),		
--------------------------------------------------------------------
-- UA
--------------------------------------------------------------------
		("LOC_TRAIT_CIVILIZATION_SUK_AHMUDAN_CONSCRIPTION_NAME",  
		"아무단 징병제"	),
		("LOC_TRAIT_CIVILIZATION_SUK_AHMUDAN_CONSCRIPTION_DESCRIPTION",  
		"주둔지, 성지, 극장가를 건설할 때마다 [ICON_Culture] 문화와 [ICON_Faith] 신앙을 획득합니다. 이 특수지구들은 도시의 근접, 대기병, 기병 유닛 생성에 대한 [ICON_Production] 생산력 +5%를 제공합니다."), 
--------------------------------------------------------------------
-- Cities
--------------------------------------------------------------------
		("LOC_CITY_NAME_SUK_BURMA_PEGU",
		"페구"),
		("LOC_CITY_NAME_SUK_BURMA_TAUNGOO",
		"따웅우"),
		("LOC_CITY_NAME_SUK_BURMA_BASSEIN",
		"바세인"),
		("LOC_CITY_NAME_SUK_BURMA_MARTABAN",
		"마르타반"),
		("LOC_CITY_NAME_SUK_BURMA_MERGUI",
		"메르귀"),
		("LOC_CITY_NAME_SUK_BURMA_PROME",
		"프롬"),
		("LOC_CITY_NAME_SUK_BURMA_MYAUNGMYA",
		"미아웅미아"),
		("LOC_CITY_NAME_SUK_BURMA_THAN_HLYIN",
		"탄린"),
		("LOC_CITY_NAME_SUK_BURMA_RANGOON",
		"랑군"),
		("LOC_CITY_NAME_SUK_BURMA_MANDALAY",
		"만달레이"),
		("LOC_CITY_NAME_SUK_BURMA_PAGAN",
		"파간"),
		("LOC_CITY_NAME_SUK_BURMA_TAVOY",
		"타보이"),
		("LOC_CITY_NAME_SUK_BURMA_SANDOWAY",
		"산도웨이"),
		("LOC_CITY_NAME_SUK_BURMA_MYOHAUNG",
		"묘하웅"),
		("LOC_CITY_NAME_SUK_BURMA_SHWEBO",
		"슈웨보"),
		("LOC_CITY_NAME_SUK_BURMA_AKYAB",
		"아키아브"),
		("LOC_CITY_NAME_SUK_BURMA_NAYPYIDAW",
		"네피도"),
		("LOC_CITY_NAME_SUK_BURMA_MOULMEIN",
		"몰멘"),
		("LOC_CITY_NAME_SUK_BURMA_MYITKYINA",
		"미치나"),
		("LOC_CITY_NAME_SUK_BURMA_SAGAING",
		"사가잉"),
		("LOC_CITY_NAME_SUK_BURMA_HSENWI",
		"센위"),
		("LOC_CITY_NAME_SUK_BURMA_TAUNGGYI",
		"따웅지"),
		("LOC_CITY_NAME_SUK_BURMA_KENGTUNG",
		"켕퉁"),
		("LOC_CITY_NAME_SUK_BURMA_MOHNYIN",
		"몬인"),
		("LOC_CITY_NAME_SUK_BURMA_TAUNGYO",
		"따웅요"),
		("LOC_CITY_NAME_SUK_BURMA_WIZAYAPURA",
		"위자야푸라"),
		("LOC_CITY_NAME_SUK_BURMA_THATON",
		"타톤"),
		("LOC_CITY_NAME_SUK_BURMA_MONYWA",
		"모니와"),
		("LOC_CITY_NAME_SUK_BURMA_NYAUNG_U",
		"니앙우"),
		("LOC_CITY_NAME_SUK_BURMA_HANLIN",
		"한린"),
		("LOC_CITY_NAME_SUK_BURMA_YE",
		"예"),
		("LOC_CITY_NAME_SUK_BURMA_HSIPAW",
		"시뽀"),
		("LOC_CITY_NAME_SUK_BURMA_MOMEIK",
		"모메익"),
		("LOC_CITY_NAME_SUK_BURMA_MONG_NAI",
		"몽 나이"),
		("LOC_CITY_NAME_SUK_BURMA_MOGAUNG",
		"모가웅"),
		("LOC_CITY_NAME_SUK_BURMA_KALAYMYO",
		"칼라이묘"),
		("LOC_CITY_NAME_SUK_BURMA_KYAUKSE",
		"캬욱세"),
		("LOC_CITY_NAME_SUK_BURMA_TAUNGDWINGYI",
		"따웅드윈지"),
		("LOC_CITY_NAME_SUK_BURMA_THARRAWADDY",
		"타라와디"),
		("LOC_CITY_NAME_SUK_BURMA_CHAUK",
		"차욱"),
		("LOC_CITY_NAME_SUK_BURMA_DONWUN",
		"돈운"),
		("LOC_CITY_NAME_SUK_BURMA_NYAUNGSHWE",
		"니앙슈웨"),
		("LOC_CITY_NAME_SUK_BURMA_MINBU",
		"민부"),
		("LOC_CITY_NAME_SUK_BURMA_SALIN",
		"살린"),
		("LOC_CITY_NAME_SUK_BURMA_BHAMO",
		"바모"),
		("LOC_CITY_NAME_SUK_BURMA_MONG_YANG",
		"몽 양"),
		("LOC_CITY_NAME_SUK_BURMA_INGAPU",
		"잉아푸"),
		("LOC_CITY_NAME_SUK_BURMA_YAMETHIN",
		"야메틴"),
--------------------------------------------------------------------
-- Citizens
--------------------------------------------------------------------
		("LOC_CITIZEN_SUK_BURMA_MALE_1",
		"누"),
		("LOC_CITIZEN_SUK_BURMA_MALE_2",
		"탄트"),
		("LOC_CITIZEN_SUK_BURMA_MALE_3",
		"마웅"),
		("LOC_CITIZEN_SUK_BURMA_MALE_4",
		"투라"),
		("LOC_CITIZEN_SUK_BURMA_MALE_5",
		"티하"),
		("LOC_CITIZEN_SUK_BURMA_MALE_6",
		"제야"),
		("LOC_CITIZEN_SUK_BURMA_MALE_7",
		"운나"),
		("LOC_CITIZEN_SUK_BURMA_MALE_8",
		"아웅"),
		("LOC_CITIZEN_SUK_BURMA_MALE_9",
		"아룬"),
		("LOC_CITIZEN_SUK_BURMA_MALE_10",
		"뉸트"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_1",
		"산다"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_2",
		"탄다"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_3",
		"티리"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_4",
		"카이"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_5",
		"야다나르"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_6",
		"타이"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_7",
		"미츠"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_8",
		"말라르"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_9",
		"틴자"),
		("LOC_CITIZEN_SUK_BURMA_FEMALE_10",
		"폰"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_1",
		"아웅 민"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_2",
		"민트 냔"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_3",
		"킨 뉸트"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_4",
		"탄 파잉"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_5",
		"스웨 린 아웅"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_6",
		"탄 토 아웅"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_7",
		"아웅 쩌 우"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_8",
		"윈 민 툿"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_9",
		"마웅 마웅 린"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_MALE_10 ",
		"랑 보 보"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_1",
		"예 라이"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_2",
		"킨 치"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_3",
		"틴 레이 느웨"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_4",
		"아예 아예 탄트"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_5",
		"테인 틴"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_6",
		"마이 미앗 노에"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_7",
		"산 산 트웨"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_8",
		"아예 티리"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_9",
		"킨 퓨"),
		("LOC_CITIZEN_SUK_BURMA_MODERN_FEMALE_10",
		"마이 툰"),
--------------------------------------------------------------------
-- Info
--------------------------------------------------------------------
		("LOC_CIVINFO_SUK_BURMA_LOCATION",
		"아시아"),
		("LOC_CIVINFO_SUK_BURMA_SIZE",
		"약 67,6000제콥킬로미터"),
		("LOC_CIVINFO_SUK_BURMA_POPULATION",
		"2014년 약 5150만 명"),
		("LOC_CIVINFO_SUK_BURMA_CAPITAL",
		"다양(파간, 페구, 아바, 랑군, 현재는 네피도)"),
--------------------------------------------------------------------
-- Named Places
--------------------------------------------------------------------
		("LOC_NAMED_RIVER_CHINDWIN_NAME",			"친드윈강"),
		("LOC_NAMED_RIVER_N_MAI_NAME",				"느마이강"),
		("LOC_NAMED_RIVER_SITTAUNG_NAME",			"시따웅강"),
		("LOC_NAMED_MOUNTAIN_PEGU_NAME",			"페구 산맥"),
		("LOC_NAMED_MOUNTAIN_SHAN_HILLS_NAME",		"샨 언덕"),
		("LOC_NAMED_MOUNTAIN_KAREN_HILLS_NAME",		"카렌 언덕"),
		("LOC_NAMED_MOUNTAIN_NAGA_HILLS_NAME",		"나가 언덕"),
		("LOC_NAMED_MOUNTAIN_TENASSERIM_NAME",		"테나세림 산맥"),
		("LOC_NAMED_MOUNTAIN_KACHIN_HILLS_NAME",	"카친 언덕"),
		("LOC_NAMED_MOUNTAIN_DAWNA_NAME",			"다우나 산맥"),
		("LOC_NAMED_VOLCANO_POPA_NAME",				"포파 산"),
------------------------------------------------------------------
-- Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_1",
		"미얀마는 동남아시아의 국가이다. 동남아시아 본토 내에서 가장 면적이 거대한 국가이며, 면적으로는 아시아에서 10번째로 거대한 국가이다."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_2",
		"1989년 이전에는 버마라는 국명이 사용되었다. 미얀마의 군사 정권은 '버마'라는 호칭은 영국 식민지 시대의 잔재인데다가 버마족 외에 다른 소수 민족을 아우르지 못한다면서 135개의 소수민족을 아우르는 명칭인 미얀마로 국호를 변경하였다. 현재도 민주화 운동을 하는 활동가들은 군사 정권에서 붙인 국명인 미얀마와 현 국기를 거부하고, 버마라는 호칭과 옛 국기를 고집하고 있다."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_3",
		"고대 미얀마에서는 북부에서는 쀼족이 살고 있었으며, 남부에서는 몬족이 모여 왕국들을 세워 살고 있었다. 이후 9세기경, 현재 미얀마의 주류를 이루는 민족인 버마족이 들어와 1050년대에 버간 왕국을 세웠고, 점차 세를 넓혀 나가며 버마족의 언어, 문화, 상좌부 불교를 중심으로 미얀마만의 독특한 문화를 만들어냈다."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_4",
		"그러나 버간 왕국은 몽골족의 대침공으로 인하여 멸망하고 말았고, 그 자리에서 여러 소왕국들이 난립하여 패권을 다투었다. 그러다가 16세기에 따웅우 왕조에 의하여 통일되었고, 이후 잠시 동안이나마 동남아 역사상 최대의 제국으로 군림하기도 하였다."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_5",
		"19세기 초반에는 꼰바웅 왕조가 현재의 미얀마 지역과 함께 마니푸르와 아삼 지역까지 통치하였다. 그러나 영국-버마 전쟁에서 패배한 직후부터는 점차 영국 동인도회사에게 국권을 침탈당하기 시작하였으며, 결국에는 영국의 식민지로 전락하였다."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_6",
		"2차 세계대전 동안 잠시동안 일본 제국의 침략을 받아 일본의 지배를 받았으며, 연합국에 의하여 해방되어 1948년에 독립을 쟁취해냈다. 그러나 독립한지 얼마 되지 않은 1962년에 네윈 주도의 군사 쿠데타가 일어나 독재가 시작되었다."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_7",
		"미얀마는 독립 이후 거의 대부분의 기간 동안 주류인 버마족과 수적 열세인 소수민족들 간의 민족 분쟁으로 인하여 기나긴 내전을 겪어 왔다. 이 내전이 워낙 격렬했기에, 수많은 인권 탄압과 잔인한 학살들이 벌어지며 인류 역사상 최악의 인명피해를 냈다는 불명예를 안기도 하였다."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_8",
		"그러던 중, 결국 2011년에 군부가 2010년 총선의 결과를 수용하면서 군부 정권은 공식적으로 해산하였고, 그 자리를 문민 정부가 들어서 민주주의의 기틀을 놓았다. 이후 국부인 아웅 산의 딸인 아웅산수치 등이 권력을 잡았고, 이후 경제적 제재를 완화하고 외교 갈등을 해소하면서 인권, 경제 부문 전반적으로 상당한 진전을 거두었다."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_9",
		"그러나 이때마저도 소수 민족에 대한 갈등이 완전히 해소된 것은 아니어서, 종교적, 민족적 충돌은 여전하였다. 2015년에 치러진 총선에서 아웅산 수치가 이끄는 당이 상원과 하원 모두에서 다수당의 지위를 차지하는 데에 성공하였고, 문민정부와 민주주의를 더더욱 굳히는 것처럼 보였다."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_BURMA_CHAPTER_HISTORY_PARA_10",
		"그러나 총선 결과에 반발한 군부가 민 아웅 흘라잉을 중심으로 결국 2021년 2월 1일에 쿠데타를 일으켰고, 권력을 장악하며 막 자라나던 민주주의의 싹을 짓밟고 말았다."),				
--========================================================================================================================
-- Myinsi
--========================================================================================================================
		("LOC_UNIT_SUK_MYINSI_NAME",  
		"민시"	),
		("LOC_UNIT_SUK_MYINSI_DESCRIPTION",  
		"버마 특유의 르네상스 시대 중기병 유닛입니다. 특수지구를 점유하고 있거나 특수지구에 인접해 있으면 [ICON_Strength] 전투력 +3을 획득하고, 해당 특수지구가 도심부나 주둔지라면 [ICON_Strength] 전투력 +3을 추가로 획득합니다."),
		("LOC_UNIT_SUK_MYINSI_DESCRIPTION_XP2",  
		"흉갑기병을 대체하는 버마 특유의 르네상스 시대 유닛입니다. 흉갑기병보다 약간 약하지만 더 빨리 해금되며 자원을 요구하지 않습니다. 특수지구를 점유하고 있거나 특수지구에 인접해 있으면 [ICON_Strength] 전투력 +3을 획득하고, 해당 특수지구가 도심부나 주둔지라면 [ICON_Strength] 전투력 +3을 추가로 획득합니다."),

		("LOC_PEDIA_UNITS_PAGE_UNIT_SUK_MYINSI_CHAPTER_HISTORY_PARA_1",  
		"민시는 버마의 기병 장교입니다. 일반적으로 기병이 50명 이상인 부대에서 수행합니다. 17세기부터 기병 부대는 일반적인 연대의 약 10%를 차지했습니다. 기병은 주로 마 상부의 세습 마을에서 징집되었습니다."),

		("LOC_ABILITY_MYINSI_DISTRICT_COMBAT_MODIFIER_DESCRIPTION",  
		"특수지구를 점유하고 있거나 특수지구에 인접해 있으면 전투력 +{1_Amount}"	),
		("LOC_ABILITY_MYINSI_ENCAMPMENT_OR_CITY_COMBAT_MODIFIER_DESCRIPTION",  
		"도심부 또는 주둔지를 점유하고 있거나 해당 특수지구에 인접해 있으면 전투력 +{1_Amount}"	),		
--========================================================================================================================
-- Paya
--========================================================================================================================
		("LOC_IMPROVEMENT_SUK_PAYA_NAME",  
		"파야"	),
		("LOC_IMPROVEMENT_SUK_PAYA_DESCRIPTION",  
		"버마 특유의 파야 건설을 위한 건설자 능력을 잠금 해제합니다.[NEWLINE][NEWLINE][ICON_Culture] 문화 +1 및 [ICON_PRODUCTION] 생산력 +1을 제공합니다. 농장이 인접해 있으면 [ICON_Culture] 문화 +1을 제공합니다. 도시에서 새롭게 생산된 지상 유닛은 파야당 [ICON_Strength] 전투력 +1을 획득합니다. 초원, 초원 원덕, 평원, 평원 언덕 타일에만 지을 수 있습니다. 다른 파야 옆에 지을 수 없습니다."),
		("LOC_PEDIA_IMPROVEMENTS_PAGE_IMPROVEMENT_SUK_PAYA_CHAPTER_HISTORY_PARA_1",  
		"미얀마는 파고다가 두드러져 '파고다의 땅'이라는 이름이 붙었습니다. 이 나라에서 파고다가 많은 것으로 유명한 도시로는 만달레이와 바간이 있습니다. 버마어에서 파고다는 많은 용어로 불립니다. 이들을 포괄하는 두드러지는 용어는 산스크리어에서 유래한 '파야'입니다. 이는 파고다, 부처상뿐만 아니라 부처, 왕, 승려 등 왕실과 종교계의 인사들 또한 지칭합니다."),		
		("LOC_IMPROVEMENT_SUK_PAYA_COMBAT_MODIFIER_DESCRIPTION",  
		"파야로부터 전투력 +{1_Amount}"	),	
--========================================================================================================================
-- Bayinnaung
--========================================================================================================================
		("LOC_LEADER_SUK_BAYINNAUNG_NAME",  
		"바인나웅"	),
--------------------------------------------------------------------
-- ULA
--------------------------------------------------------------------
		("LOC_TRAIT_LEADER_SUK_ALLEGIANCE_AND_OBLIGATION_NAME",  
		"복종과 의무"	),
		("LOC_TRAIT_LEADER_SUK_ALLEGIANCE_AND_OBLIGATION_DESCRIPTION",  
		"플레이어가 종주국인 모든 도시 국가에서 [ICON_Gold] 금 +3을 획득합니다. 플레이어가 처음 도시 국가의 종주국이 되면 해당 도시 국가가 중기병 유닛 1기를 무료로 제공합니다."), 
--------------------------------------------------------------------
-- Agenda
--------------------------------------------------------------------
		("LOC_AGENDA_SUK_VICTOR_OF_TEN_DIRECTIONS_NAME",  
		"열 방향의 승리자"	),
		("LOC_AGENDA_SUK_VICTOR_OF_TEN_DIRECTIONS_DESCRIPTION",  
		"자신의 대륙에 고유한 도시가 있는 모든 문명을 정복하려 합니다. 도시를 정복하는 문명을 존중합니다."	),

		("LOC_DIPLO_KUDO_LEADER_SUK_BAYINNAUNG_REASON_ANY",  
		"(정복한 도시를 소유하고 있습니다.)"	),
		("LOC_DIPLO_MODIFIER_SUK_VICTOR_OF_TEN_DIRECTIONS_KUDOS",  
		"바인나웅은 당신의 야망을 존중함"	),

		("LOC_DIPLO_WARNING_LEADER_SUK_BAYINNAUNG_REASON_ANY",  
		"(같은 대륙에 있고 정복한 도시를 소유하고 있지 않습니다.)"	),
		("LOC_DIPLO_MODIFIER_SUK_VICTOR_OF_TEN_DIRECTIONS_WARNING",  
		"바인나웅은 당신이 버마의 확장에 걸림돌이 된다고 생각함"	),
--------------------------------------------------------------------
-- RWF Support
--------------------------------------------------------------------
		("LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_SUK_BURMA",
		"우"),
		("LOC_GOVERNMENT_JFD_HORDE_LEADER_TITLE_SUK_BURMA",
		"사우브와"),
		("LOC_GOVERNMENT_JFD_POLIS_LEADER_TITLE_SUK_BURMA",
		"민"),

		("LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_SUK_BURMA",
		"보"),
		("LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_SUK_BURMA",
		"웅이"),
		("LOC_GOVERNMENT_JFD_CLASSICAL_DEMOCRACY_LEADER_TITLE_SUK_BURMA",
		"사마다"),

		("LOC_GOVERNMENT_JFD_MERCHANT_REPUBLIC_LEADER_TITLE_SUK_BURMA",
		"사마다"),
		("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_SUK_BURMA",
		"민"),
		("LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_SUK_BURMA",
		"무멧"),

		("LOC_GOVERNMENT_JFD_LIBERAL_DEMOCRACY_LEADER_TITLE_SUK_BURMA",
		"사마다"),
		("LOC_GOVERNMENT_JFD_PEOPLES_REPUBLIC_LEADER_TITLE_SUK_BURMA",
		"오카타"),
		("LOC_GOVERNMENT_JFD_MILITARY_GUARDIANSHIP_LEADER_TITLE_SUK_BURMA",
		"보죠케"),			
		
		("LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_SUK_BURMA",
		"세캬와디"),																					
--------------------------------------------------------------------
-- Diplo
--------------------------------------------------------------------
		("LOC_LOADING_INFO_LEADER_SUK_BAYINNAUNG",  
		"바인나웅 왕이시여, 앞으로 나아가십시오! 당신의 주변에 있는 국가들을 복종시키십시오! 당신의 외교와 군사력은 세계의 왕들에게 충성을 강요할 것이며, 그들의 공물은 언제나 당신의 군대가 나아가는 원동력이 될 것입니다. 그들의 복종과 의무는 당신이 버마의 영광을 전 지구에 전파하는 데 도움을 줄 것입니다."  	),
		("LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"실망스럽군."),
		("LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"나로선 영광이오."),
		("LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"그대는 엄청난 잠재력을 보였소. 우리 친선을 맺어 협업합시다!"),
		("LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"안되오. 그대는 먼저 자신을 증명해야 하오."),
		("LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"영광이오."),
		("LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"오랫동안 고민했소. 그대는 나의 많은 종속국에 가담할 때요."),
		("LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"또 배신인가? 내가 너무 순진했군."),
		("LOC_DIPLO_DEFEAT_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"나의 종속국이 부족했던 모양이군. 그대의 승리를 축하하오."),
		("LOC_DIPLO_DEFEAT_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"나의 종속국이 부족했던 모양이군. 그대의 승리를 축하하오."),
		("LOC_DIPLO_DELEGATION_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"그대의 백성을 위해 석가상을, 그대를 위해 론지를 보냈소."),
		("LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"수락할 수 없소."),
		("LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"고맙소. 버마에 공물은 언제나 환영이오."),
		("LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"내가 개입하여 그대를 말려야겠소. 그대는 통치에 적합한 인물이 아니오. (공개 비난)"),
		("LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"또 배신이군. 내가 너무 순진했다는 걸 알게 됐소."),
		("LOC_DIPLO_FIRST_MEET_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"그대는 버마의 왕 바인나웅 쩌틴 나우라타를 만나는 영예를 누리고 있소. 그대의 힘과 우리가 동맹이 될 수 있다는 것을 증명해보시오."),
		("LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"인근에 우리 도시가 있는데, 지금 생각해보니 그게 내 도시인지 종속국 도시인지 헷갈린다오."),
		("LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"멋지군."),
		("LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"일꾼들이 방금 내 궁전에 마무리 손질을 끝냈소. 그대가 그 화려함을 볼 수 있도록 초대하겠소."),
		("LOC_DIPLO_GREETING_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"환영하오."),
		("LOC_DIPLO_WARNING_EXIT_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"조심하시오. 그대의 작은 나라는 버마의 영광에 걸림돌이 되고 있소."),
		("LOC_DIPLO_KUDO_EXIT_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"그대의 정복을 흥미 있게 지켜봤소. 실로 인상적이더군."),
		("LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"나와 함께하시오! 그대의 힘은 감탄할 만하오!"),
		("LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"{LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY}"),
		("LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"{LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY}"),
		("LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"잘 싸웠소. 이제 우리는 평화를 얻었소."),
		("LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"안되오. 받아들일 수 없소."),
		("LOC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"그대는 패기를 충분히 증명했소. 이 전쟁을 끝냅시다."),
		("LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"허락하지만 오래 머물지는 마시오."),
		("LOC_DIPLO_REJECT_OPEN_BORDERS_FROM_HUMAN_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"어떤 장군이 이런 걸 허락하겠소?"),
		("LOC_DIPLO_OPEN_BORDERS_FROM_AI_LEADER_SUK_BAYINNAUNG_ANY",                                     
		"그대의 영토를 지나가길 원하오. 이건 생명이 걸린 문제요."),
		("LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_SUK_BAYINNAUNG_ANY",                                      
		"그대가 우리를 군대로 위협하고자 해도 소용 없소. 그들을 이동시키지 않으면 안 좋은 결과를 맞이할 것이오."),
--------------------------------------------------------------------
-- Quote and Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_LEADERS_PAGE_SUK_BAYINNAUNG_QUOTE",  
		"버마와 아유타야가 네 마리의 백색 코끼리를 가지고 있는 한, 이들은 물과 대지와도 같을 것이다."  	),
		("LOC_PEDIA_LEADERS_PAGE_SUK_BAYINNAUNG_TITLE",
		"바인나웅"),
		("LOC_PEDIA_LEADERS_PAGE_SUK_BAYINNAUNG_SUBTITLE",
		"따응우 왕조의 제5대 왕이자 정복군주"),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_CAPSULE_BODY",
		"버마 제국은 문화와 신앙이 작용하여 군대를 비할 바 없이 지원해주는 제국입니다. 바인나웅은 버마의 군사력을 강화하겠다는 그의 의지에 따라 도시국가들을 굴복시켰습니다."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_DETAILED_BODY",
		"버마는 처음에는 매우 유연한 문명입니다. 성지, 극장가, 또는 주둔지를 건설하면 [ICON_Faith]신앙과 [ICON_Culture]문화에 작은 힘을 실어주며, 군대를 빠르게 편성하는 데 있어 두 번째 특별한 특성을 사용할 때 뒤처지지 않도록 도와줍니다. [ICON_Culture]문화를 제공하고 군대의 전력을 강화하여 문화와 군사력을 더욱 강화하며 바인나웅 휘하에서는 도시국가들이 신속하게 가치 있는 종주국임을 증명할 것이며, 무료로 중기병 유닛을 제공하고 [ICON_Gold]금을 제공할것입니다."),		
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_1",
		"바인나웅은 따웅우 왕조의 제5대 국왕으로, 활발한 정복 사업을 펼친 군주이며, 강력한 일원적 통합 정책을 펼친 법치의 군주이고, 계관시인을 둔 문화 군주이기도 했다. 전 왕인 떠빈슈웨티의 의형이며, 떠빈슈웨티의 여동생과 결혼하여 '왕의 형'이라는 뜻인 '버인나웅'으로 불리게 되었다."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_2",
		"버마를 통일했던 떠빈슈웨티의 치세 말기에는 스밈 토라는 버고 왕실의 후예가 버고 왕손들을 규합하여 반란을 일으켰는데, 바인나웅이 이 반란을 진압하기 위해 다곤에 있던 차에 떠빈슈웨티가 사망하였다. 그러자 혼란한 정국 속에서 버고, 삐는 반란을 일으켰다. 바인나웅은 일단 곧바로 휘하 군사를 이끌고 도성인 따웅우 성으로 향해 이를 접수하고 따웅우 왕조의 새로운 왕위에 올랐다."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_3",
		"바인나웅은 즉위 후 우선 따웅우에서 가까운 반란세력인 삐를 공격했는데, 삐의 왕은 바인나웅의 진격 소식을 듣자 도주했으나 붙잡혀 처형되었다. 다음으로 그 사이 버고의 왕위에 오른 스밈 토를 공격하였다. 스밈 토는 처음에 바인나웅을 업신여겨 일기토를 제의했으나, 곧 이를 수락한 바인나웅의 기세에 질려 도주하다 붙잡혀 죽었다. 이로써 다시 삐와 버고는 따웅우 왕조의 지배 아래로 편입되었다."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_4",
		"바인나웅은 국내의 반란을 진압하고 왕국을 안정시킨 데 머무르지 않고 더욱 광범위한 정복 사업을 펼쳤다. 그는 먼저 잉와를 복속시키고 샨족을 버마의 지배 하에 두었다. 1558년에는 타이 북부 치앙마이의 란나 왕국을 점령하여 이 지역도 통치하게 되었다. 란나의 왕은 바인나웅의 정복 후 따웅우의 일개 영주로 강등되었다. 란나 왕국은 원래 타이계 국가로 버마족과는 이질적이었는데, 바인나웅은 이 지역을 정복한 후 불경의 사본과 승려들을 보내고 불교 건축물들을 세워 고급 불교 문화를 활발히 전파했다. 치앙마이에서 다수의 장인과 기술자들을 버마로 데리고 와 버고에 정착해 살도록 하기도 했다."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_5",
		"따웅우 왕조가 란나 왕국을 관할 하에 두었다는 정보가 주변으로 퍼지자 버마-중국 접경지대의 샨족들은 자발적으로 바인나웅에게 항복해 왔고, 윈난의 일부 족장들도 버마의 영향력을 인정하고 동맹을 맺었다. 또한 접경한 인도계 지역인 마니푸르의 군주들도 따웅우 왕조에 조공을 보내게 되었다."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_6",
		"바인나웅은 기세를 몰아 끊임없는 팽창 정책을 펼쳐, 1559년에 이르자 현재의 미얀마 영토 대부분과 인도의 마니푸르, 현 라오스 지역인 란쌍 왕국의 수도 비엔티안까지 점령하게 되었다. 또 1563년부터는 남부 타이의 아유타야 왕조에 대한 본격적인 공격에 들어가 타이족 지역인 깜팽펫과 수코타이를 점령하고 1564년에는 마침내 수도 아유타야를 점령하여 결국 아유타야 왕국 전역을 버마의 속령으로 만들었다. 바인나웅의 군대는 아유타야 왕 및 대신들의 가솔들을 포함한 3천여 명의 포로를 데리고 아유타야의 소유였던 30여 개의 대형 청동 부처상 및 다량의 금은보화 등의 전리품을 얻어 버마 본토로 개선하였다."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_7",
		"남북 타이의 정복에도 만족하지 못한 바인나웅은 이후에도 계속해서 끊임없이 주변을 공격했다. 심지어 1581년 66세의 나이로 숨을 거두는 순간까지도 라카인의 정복을 위해 군대의 이동을 명령했을 정도였다."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_8",
		"바인나웅은 활발한 정복 사업으로 거대해진 국토 내의 모든 종족에게 하나의 통일된 법, 문자(버마 문자), 도량형을 사용하게 하여 따웅우의 신민으로서의 일체감을 갖도록 하였다. 이를 위해서는 법전이 필요해 법전의 집필을 명하였고, 명을 받은 12인 승려 위원회에서는 마침내 버마 법전 요설을 만들었다. 이 외에도 다수의 법률가들이 활동하여 버마 및 피정복 지역의 관습법을 한데 묶어 정리하기도 했다. 또 여러 부문에서 강력한 법적 통제를 행하였는데, 대표적으로 산 짐승들을 무단으로 도살하는 행위에 대해 칙령을 내려 엄격히 통제한 일을 들 수 있다."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_9",
		"그러나 이렇게 강력한 통제조차도 그가 점령한 과도하게 많은 영토를 통합하기에는 역부족이었다. 바인나웅의 철권에 의해 그나마 유지되던 정복지의 치안은 그의 사후 급격히 나빠져 대대적인 반란이 발생하였다. 뒤를 이은 난다버인은 나름대로 통합 정책을 구사하며 반란지를 재정복하려 하였으나 능력 부족으로 실패하고 하부 버마와 란쌍 왕국의 지배권을 잃었으며, 속령이었던 아유타야의 나레수안 대왕에게도 대패하여 남북 타이의 지배권을 잃었다."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_BAYINNAUNG_CHAPTER_HISTORY_PARA_10",
		"바인나웅은 잦은 정복 사업으로 인해 버마에 상당한 인명 피해를 불러 일으켰다. 따웅우의 백성들은 하루가 멀다 하고 벌어지는 정복 전쟁 때문에 언제 징집되어 전선에 나갈 일이 생길지 몰라 불안에 떨어야 했으며, 농사를 지을 장정들의 수도 크게 줄어 농토가 방치되어 황무지로 변하는 일도 잦았다. 이와 더불어 법치와 강력한 중앙의 일원적 통제를 강조하는 엄한 면모로 백성들의 심적 지지도 얻지 못하였다. 이에 바인나웅의 시대에는 백성들의 원성이 자자하였다.");			
--------------------------------------------------------------------
--------------------------------------------------------------------